// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABaHGLjDCZrS_-wbeLGbZnRQkHfcyuBh4',
    appId: '1:510064080994:web:1d2e1c1b2da14a8db9393b',
    messagingSenderId: '510064080994',
    projectId: 'delevery-app-2c5e8',
    authDomain: 'delevery-app-2c5e8.firebaseapp.com',
    storageBucket: 'delevery-app-2c5e8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsyd7Xsmgud2-L2xKBxEZBwkcgw53TgtE',
    appId: '1:510064080994:android:8a10df176d6460cab9393b',
    messagingSenderId: '510064080994',
    projectId: 'delevery-app-2c5e8',
    storageBucket: 'delevery-app-2c5e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDihO2N42a_tA5Ys_mIiFlvKAszWD9SN1I',
    appId: '1:510064080994:ios:b8b6d419ef81d53fb9393b',
    messagingSenderId: '510064080994',
    projectId: 'delevery-app-2c5e8',
    storageBucket: 'delevery-app-2c5e8.appspot.com',
    iosClientId: '510064080994-63njulguscuslqmmjm538agvlac5uk32.apps.googleusercontent.com',
    iosBundleId: 'com.example.deleverApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDihO2N42a_tA5Ys_mIiFlvKAszWD9SN1I',
    appId: '1:510064080994:ios:ef416f0c99044a3fb9393b',
    messagingSenderId: '510064080994',
    projectId: 'delevery-app-2c5e8',
    storageBucket: 'delevery-app-2c5e8.appspot.com',
    iosClientId: '510064080994-p07uvtj4fci7k95nok588l4p7gnb84o6.apps.googleusercontent.com',
    iosBundleId: 'com.example.deleverApp.RunnerTests',
  );
}
